### ISSUE TITLE
Resharper is having issues with finding views

### ISSUE THREAD

**Issue by TotzkePaul** [OdeToCode/AddFeatureFolders#10]
Microsoft Visual Studio Enterprise 2017
Version 15.1 (26403.7) Release

In the controllers, Resharper highlights "View()" as red and says "Cannot resolve View 'ViewName'.

I target ".NETCoreApp 1.1" while AddFeatureFolders project targets "v4.5.2". Resharper doesn't have any issues when I open and run AddFeatureFolders.

Everything else works except that Resharper can't find views. I know this is a Resharper specific issue but I saw that you used Resharper inspection comments and that you might already have a fix for it.

**Comment by kasparkallas** [comment]
I haven't tried it out but the issue you describe seems to be fixed according to ReSharper's issue tracker: https://youtrack.jetbrains.com/issue/RSRP-461882

**Comment by TotzkePaul** [comment]
My properties folder doesn't have a AspMvcViewLocationFormatAttribute.cs. I tried adding one but still didn't clear it up.

**Comment by kasparkallas** [comment]
I think you need to install JetBrains ReSharper Annotations NuGet.

**Comment by TotzkePaul** [comment]
Updating to Resharper 2017.1.1 fixed it.
