### ISSUE TITLE
Usage with API?

### ISSUE THREAD

**Issue by CMTietgen** [OdeToCode/AddFeatureFolders#11]
I just watched a YouTube video where you briefly discussed **AddFeatureFolders** and it piqued my interest.

Can it be used for an API written using .NET Core?

Sorry for my ignorance, I'm just starting to learn .NET Core and MVC/APIs in general.

**Comment by kasparkallas** [comment]
Do you mean ASP.NET Web API? If so then yes you can.

**Comment by OdeToCode** [comment]
Yes, in fact you don't even need this package. This package helps ASP.NET Core locate the views associated with a controller. API controllers typically won't use a view engine, and the API controllers can be placed into whatever folder structure you desire.
