### ISSUE TITLE
Usage with view components

### ISSUE THREAD

**Issue by kasparkallas** [OdeToCode/AddFeatureFolders#12]
Today I learned about [view components](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-components) and they seem to have a strict unconfigurable convention for finding component views.

Is there are a cleaner way to use view components with feature folders other than to explicitly specify the full view path when returning a view from a component?

**Comment by OdeToCode** [comment]
I've used shared view components (Features\Shared) without specifying the full path. Are you using a view component that is restricted to use from a specific feature? I'll have to try that scenario, but I think it should work without a full path.

**Comment by kasparkallas** [comment]
A quick test revealed that a view component invoked from _Features/Projects_ seemed to look for its view only from _Features/_. I don't understand how it came up with that path... I'll soon investigate it further.

**Comment by kasparkallas** [comment]
I have been lazy and haven't investigated further. In the one place I currently use a `ViewComponent` I just specify the path directly like so `return View("~/_Features/ProjectList/ProjectListPartial.cshtml");` and that's good enough with ReSharper navigation support.

**Comment by lastsignal** [comment]
This is still an issue. Couldn't get it to work. It doesn't understand {0} and {1}. When hard coded, it works.
