### ISSUE TITLE
_Layout not displayed in .Net core 2.0 preview 1

### ISSUE THREAD

**Issue by Ponant** [OdeToCode/AddFeatureFolders#16]
Hi @OdeToCode ,
Did you encounter a bug with the FeaturesFolder with .Net Core 2.0 Preview 1? I was working without issues on .Net Core 1.1 with your routine and the views were properly discovered, but now starting with an empty template in preview 1 and adding a home/index view with a controller and attribute routing and a shared layout view gets the latter not displayed by a browser. The only way to have it read is to invoke `Layout = "_Layout"; ` directly from Home Index view.

**Comment by OdeToCode** [comment]
Good question, I haven't tried this package with 2.0 myself, was waiting for it to get a bit closer to a release candidate status.

**Comment by Ponant** [comment]
Unfortunately, I confirm the existence of this bug as I took a fresh new template and added your nuget. If you have an idea on what I should look for I would be happy to tackle it. I get the following warning, not sure if this is related.
`Microsoft.IdentityModel.Clients.ActiveDirectory 3.13.5 depends on System.Net.Http (>= 4.0.1) but System.Net.Http 4.0.1 was not found. An approximate best match of System.Net.Http 4.1.0 was resolved.
`

**Comment by OdeToCode** [comment]
Does the empty template include a _viewstart file?

**Comment by Ponant** [comment]
No, it's empty as before...

**Comment by Ponant** [comment]
Of course I added it

**Comment by Ponant** [comment]
Here is a repro
https://github.com/Ponant/LayoutFeature and discussion here
https://github.com/aspnet/Mvc/issues/6448

**Comment by Ponant** [comment]
@OdeToCode , the workaround is now on the aspnet/mvc repo. It is not due to your package. Wise to wait for the official release.
https://github.com/aspnet/Mvc/issues/6448
