### ISSUE TITLE
[Feature Request] Views folder within the Individual Feature folder

### ISSUE THREAD

**Issue by flatproject** [OdeToCode/AddFeatureFolders#18]
I tried to add a Views folder within my Feature folder but the view cannot be located.

Looking at the source code i understand that it is not currently possible.

What i'm looking for is this setup:

> Features -> FeatureFoo -> Views

I'm only asking for it because moving the Account and Manage Views of the default VS MVC template with Individual Auth looks messy.

Please consider it. Thank you.

**Comment by OdeToCode** [comment]
I've done this a few times and you can just drag and drop the views, controllers, and models into feature folders. The harder part is adjusting the namespaces for controllers and models. A tool like Resharper can help there.

**Comment by mxmissile** [comment]
I think you can do this with the new Areas update:

```
var options = new AreaFeatureFolderOptions 
{
   DefaultAreaViewLocation = @"\Features\{1}\Views\{0}.cshtml";
}
```

**Comment by OdeToCode** [comment]
Good solution!
