### ISSUE TITLE
Project doesnt work when referencing

### ISSUE THREAD

**Issue by Gillardo** [OdeToCode/AddFeatureFolders#19]
If i install this package it is never able to be referenced in my project.  I am guessing something in old in this project that is stopping it being referenced.

Shame as would love to use, i have copied your code and put it directly into my project and it works fine....

Any reason this shouldnt work?

I am targeting net461 in my project and referencing 1.1.* packages from aspnetcore.

**Comment by OdeToCode** [comment]
I haven't been able to reproduce. Are you seeing an error message at any point?

**Comment by Gillardo** [comment]
Seems to now work... strange
