### ISSUE TITLE
Adding a second controller action throws AmbiguousActionException

### ISSUE THREAD

**Issue by TDK1964** [OdeToCode/AddFeatureFolders#20]
Adding a second controller action throw an exception

```
public IActionResult Create()
{
    return View();
}
```
An unhandled exception occurred while processing the request.
AmbiguousActionException: Multiple actions matched. The following actions matched route data and had all constraints satisfied:

WebApplication.Features.Foo.HomeController.Home (WebApplication)
WebApplication.Features.Foo.HomeController.Create (WebApplication)
Microsoft.AspNetCore.Mvc.Internal.ActionSelector.SelectBestCandidate(RouteContext context, IReadOnlyList<ActionDescriptor> candidates)

**Comment by OdeToCode** [comment]
Sounds like you do not have a route that allows for an action to be defined in the route. Feature folders still use the MVC routing rules. 

If you want to add a second action to the HomeController in the sample project, you'll have to add a route that has action information (like Route("[controller]/[action]")
