### ISSUE TITLE
Index view not loading without action in URL

### ISSUE THREAD

**Issue by Gillardo** [OdeToCode/AddFeatureFolders#25]
I dont seem to be able to load my index view without putting index in the url.

for example, i should be able to go to http://localhost:5000/serverRoute and it should load, however it doesnt.  I need to check the path to http://localhost:5000/serverRoute/index in order for it to load.

Is this right?

My route is slightly different as i am using SPA, and looks like this
```
// routes
app.UseMvc(routes =>
{
	// default goes to Home, and angular will deal with client side routing		
	routes.MapRoute(
		name: "default",
		template: "{*url}",
		defaults: new { controller = "home", action = "index" });
});
```

Help much appreicated

**Comment by OdeToCode** [comment]
I tested this on my own project and it works fine (all requests go to the HomeController in a Features\Home folder). The Index view is in the same folder. Make sure you don't have a Route attribute on the controller, and the controller is using a namespace that matches the path to the folder. In other words, if you have a Features\Home folder with the controller and view, the Controller should be in a namespace like <projectname>.Features.Home
