### ISSUE TITLE
Are the default controller and action the wrong way round?

### ISSUE THREAD

**Issue by Gillardo** [OdeToCode/AddFeatureFolders#26]
As you can see below the controller i am loading is called NHT and the action is INDEX, yet it is checking for a folder called Index in Features and a page called NHT???

![image](https://user-images.githubusercontent.com/7406381/40456331-b320cb16-5ee8-11e8-98ec-0cc5f79c0c10.png)

**Comment by OdeToCode** [comment]
Is your controller in a namespace that matches the folder hierarchy?

**Comment by aabenoja** [comment]
@OdeToCode I am 90% certain this is the same as #29, so I have to wonder if [this section](https://github.com/OdeToCode/AddFeatureFolders/tree/bb88432b84aef956f4899dba0e9146517562f7e2#just-one-more-thing) of the README just isn't bold enough

**Comment by OdeToCode** [comment]
Yes, I agree.

**Comment by OdeToCode** [comment]
Made instructions stand out a bit more, removed info for project.json.
