### ISSUE TITLE
Including the word `Features` in your project namespace breaks conventions

### ISSUE THREAD

**Issue by sgwatgit** [OdeToCode/AddFeatureFolders#27]
I created a new ASP.NET Core 2.1 MVC project and named the project `ASPNETCoreMVC.Features.Web`.

I added `<PackageReference Include="OdeToCode.AddFeatureFolders" Version="2.0.1" />` to my `.csproj`.

When I run the app it says

```
An unhandled exception occurred while processing the request.
InvalidOperationException: The view 'Index' was not found. The following locations were searched:
Features\Web\Features\Home\Index.cshtml
Features\Shared\Index.cshtml
\Features\Index\Home.cshtml
```

![mvc-feature-folders-project-naming-convention-routing-error](https://user-images.githubusercontent.com/1382768/40888666-86609cb2-6728-11e8-855a-aeb3f5ff7339.PNG)

In this case I'd need to change `FeatureFolderOptions.FeatureFolderName` to something other than `Features` because 

```csharp
@namespace.Split('.')
	 .SkipWhile(s => s != _folderName)
	.Aggregate("", Path.Combine);
```

is going to stop too early and create the wrong folder path.

Here is an ugly solution

```
.AddFeatureFolders(new FeatureFolderOptions
{
    FeatureFolderName = "Features",
    DeriveFeatureFolderName = model =>
    {
        string assemblyNamespacePrefix = $"{typeof(Startup).Namespace}.";
        string @namespace = model
                .ControllerType
                .Namespace
                .Remove(0, assemblyNamespacePrefix.Length);

        string result = @namespace.Split('.')
                                .SkipWhile(s => s != "Features")
                                .Aggregate("", Path.Combine);

        return result;
    }
});
```

But maybe the best thing to do is add a disclaimer to the `README.md` that your feature folder name cannot be in the project namespace?

**Comment by OdeToCode** [comment]
Yes, I think the best change would be in the documentation.

**Comment by sgwatgit** [comment]
I can PR this.
