### ISSUE TITLE
Consider adding side-by-side support

### ISSUE THREAD

**Issue by dotnetshadow** [OdeToCode/AddFeatureFolders#3]
After reading the article you referenced by Steve Smith, I noticed he has a section on side by side support where you can still allow the traditional folder structure or areas support.

I thought it would be cool to add some options so that you can enable or disable these?

**Comment by OdeToCode** [comment]
Good idea, I'll look at adding the support.

**Comment by kasparkallas** [comment]
All you have to do to enable side-by-side support with default ASP.NET is not to clear `ViewLocationFormats` when calling `AddRazorOptions()` in `Startup` (i.e. `ServiceCollectionExtensions`).

**Comment by thiagomajesk** [comment]
I think that this behaviour should be included by default, so it doesn't break projects migrating to feature-folder approach. 

@kasparkallas That would have to be avaiable as an option like `AddFeatureFolders(overrideDefault: true)`

@OdeToCode Is this implemented yet or is there any alternatives?

**Comment by OdeToCode** [comment]
I haven't had a chance to implement this yet, no. Will leave this open.

**Comment by valdisiljuconoks** [comment]
@thiagomajesk it should be done via already existing `FeatureFolderOptions` class:

```
services.AddFeatureFolders(new FeatureFolderOptions { OverrideDefaultConventions = true });
```

**Comment by thiagomajesk** [comment]
@valdisiljuconoks This seems right. I didn't notice the presence of this configuration when I commented.

**Comment by mxmissile** [comment]
PR?

**Comment by TDK1964** [comment]
Anything happening with this enhancement?

**Comment by OdeToCode** [comment]
I have not. I think the future of feature folders will be Razor pages, so I haven't been too inclined to add more work for now.

**Comment by mxmissile** [comment]
@OdeToCode Interesting, any blog posts on the subject? Curious how and why.

**Comment by valdisiljuconoks** [comment]
IMHO Razor Pages will not be able to *replace* feature folders. at least from what I understand about razor pages and feature folders...

**Comment by TDK1964** [comment]
All good observations but can we still have the side-by-side support?

**Comment by OdeToCode** [comment]
Adding area support
