### ISSUE TITLE
Error after browsing to Login page in MVC Core app

### ISSUE THREAD

**Issue by NRKirby** [OdeToCode/AddFeatureFolders#37]
I am getting the following error

> InvalidOperationException: The layout view '/Views/Shared/_Layout.cshtml' could not be located. The following locations were searched:
/Views/Shared/_Layout.cshtml

when I browse to the Login page in a new MVC Core app

The folder structure looks like this:

![image](https://user-images.githubusercontent.com/6445534/57377370-2cadca00-719a-11e9-9b4b-61375e737517.png)

I've added the following in `ConfigureServices`
```

            services
                .AddMvc()
                .AddFeatureFolders()
                .SetCompatibilityVersion(CompatibilityVersion.Version_2_2);
```

and in `Configure`
```

app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");
            });
```

Can anyone help with this please?  I'm not sure what I'm doing wrong here

**Comment by NRKirby** [comment]
Ok so the problem was I didn't have the correct path in `_ViewStart.cshtml`, I needed to update that to:

```
/Features/Shared/_Layout.cshtml
```

**Comment by OdeToCode** [comment]
Glad you could figure that out!
