### ISSUE TITLE
sub folder and routing

### ISSUE THREAD

**Issue by philwindsor** [OdeToCode/AddFeatureFolders#38]
This is from the sample site in the repo

Main content rendered by FEATURE:Foo:SubFoo:SubFooController::SubFoo

Given this path, I would expect the url route to be

http://localhost:8557/Foo/SubFoo

and not

http://localhost:8557/SubFoo/SubFoo

I have resorted to using Routes in my controllers to achieve the desired path but just wondering why it does this?

**Comment by aabenoja** [comment]
`.AddFeatureFolders()` does not override how routes are generated. Given the following from `Configure()` in `Startup.cs`

```cs
app.UseMvcWithDefaultRoute().UseMvc(routes =>
  routes.MapRoute(
    name: "areaRoute",
    template: "{area:exists}/{controller=Home}/{action=Index}/{id?}"));
```

we still use the default routing scheme of `{controller=Home}/{action=Index}`. In this regard, your `SubFoo/SubFoo` route makes perfect sense.

**Comment by philwindsor** [comment]
ok thanks
