### ISSUE TITLE
View Component Tag Helper not working

### ISSUE THREAD

**Issue by Ponant** [OdeToCode/AddFeatureFolders#8]
Hi Scott,
Instead of using ` @await Component.InvokeAsync` , I used the html friendly `<vc></vc>` element and it does not work on the browser and no intellisense (the vc is blue instead of dark green). Other TagHelpers such as `asp-action` are properly coloured and intellisensed (if that is a verb......).
It works  properly on the ASP.NET template and I used the same tag helper ` <vc:main-menu></vc:main-menu>.` I had to add `@addTagHelper *, WebApplication` in `_ViewImports` such that it does not crash, but it does not render.
So I wonder if that is not an issue with your extension?

**Comment by Ponant** [comment]
OK, my apologies. I forgot to upgrade your proj to .Net Core 1.1................

**Comment by Ponant** [comment]
I made a new fresh project starting with .Net Core 1.1, and I can confirm that this issue is reproduced.
Upon adding
`        <vc:main-menu></vc:main-menu>`
one gets
`Error CS0400 The type or namespace name '__Generated__MainMenuViewComponentTagHelper' could not be found in the global namespace (are you missing an assembly reference?)`
Although the program runs.

**Comment by Ponant** [comment]
Tracked here, it is not your issue
[#5943](https://github.com/aspnet/Mvc/issues/5943)

**Comment by OdeToCode** [comment]
Thanks for investigating, @Ponant .
